import { ArrowDownLeft, ArrowUpRight, Bank, CalendarBlank, Wallet } from "@phosphor-icons/react/dist/ssr";
import { FeeList } from "@/components/fee-list";
import { formatDate, formatRupiah } from "@/lib/format";
import { getPortalData } from "@/lib/data";
import { getPublicCashSummary } from "@/lib/portal-services";

export const dynamic = "force-dynamic";
export const metadata = { title: "Kas OPAL", description: "Ringkasan Kas OPAL dan informasi iuran warga." };

export default async function KasPage() {
  const [summary, portal] = await Promise.all([getPublicCashSummary(), getPortalData()]);
  const hasData = summary.income || summary.expense;
  return <main>
    <section className="border-b border-line bg-surface-subtle"><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><p className="text-sm font-semibold text-brand">Kas OPAL</p><h1 className="mt-3 max-w-4xl text-balance text-4xl font-extrabold tracking-[-0.07em] text-ink sm:text-5xl lg:text-6xl">Kas yang bisa dibaca warga, detail yang tetap tepat sasaran.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-ink-muted sm:text-lg">Ringkasan di bawah hanya menampilkan pembukuan yang telah disetujui untuk publik. Riwayat iuran satu rumah tersedia melalui tautan privat yang dibagikan RT.</p></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="grid border border-line lg:grid-cols-3"><div className="border-b border-line p-6 lg:border-r lg:border-b-0"><div className="flex items-center gap-2 text-sm font-bold text-ink-muted"><ArrowDownLeft size={18} weight="bold" className="text-brand" /> Pemasukan publik</div><p className="mt-6 text-3xl font-extrabold tracking-[-0.06em] text-ink">{formatRupiah(summary.income)}</p></div><div className="border-b border-line p-6 lg:border-r lg:border-b-0"><div className="flex items-center gap-2 text-sm font-bold text-ink-muted"><ArrowUpRight size={18} weight="bold" className="text-[#a53928]" /> Pengeluaran publik</div><p className="mt-6 text-3xl font-extrabold tracking-[-0.06em] text-ink">{formatRupiah(summary.expense)}</p></div><div className="p-6"><div className="flex items-center gap-2 text-sm font-bold text-ink-muted"><Wallet size={18} weight="fill" className="text-brand" /> Saldo ringkasan</div><p className="mt-6 text-3xl font-extrabold tracking-[-0.06em] text-ink">{formatRupiah(summary.balance)}</p>{summary.lastUpdated ? <p className="mt-3 text-sm text-ink-muted">Per {formatDate(summary.lastUpdated)}</p> : null}</div></div></section>
    <section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-6 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:px-10 lg:py-10"><div><FeeList fees={portal.fees} /><div className="mt-8 border-y border-line py-5"><div className="flex items-start gap-3"><Bank size={23} className="mt-0.5 shrink-0 text-brand" weight="fill" aria-hidden="true" /><div><h2 className="font-extrabold tracking-[-0.03em] text-ink">Pembayaran Kas OPAL</h2><p className="mt-1.5 text-sm leading-6 text-ink-muted">BCA 1011815125 a.n. Neria Kezia Jayanti. Pastikan konfirmasi metode pembayaran yang berlaku kepada pengurus.</p></div></div></div></div>
      <div className="border-t border-line"><div className="flex items-center justify-between py-5"><h2 className="text-2xl font-extrabold tracking-[-0.05em] text-ink">Kategori pembukuan</h2>{summary.lastUpdated ? <span className="flex items-center gap-1.5 text-xs font-bold text-ink-faint"><CalendarBlank size={15} /> Diperbarui</span> : null}</div>{hasData ? <div className="divide-y divide-line border-y border-line">{summary.categories.map((item) => <div key={item.category} className="grid gap-2 py-5 sm:grid-cols-[1fr_auto_auto] sm:items-center sm:gap-8"><p className="font-bold text-ink">{item.category}</p><p className="text-sm text-ink-muted">Masuk <strong className="text-ink">{formatRupiah(item.income)}</strong></p><p className="text-sm text-ink-muted">Keluar <strong className="text-ink">{formatRupiah(item.expense)}</strong></p></div>)}</div> : <p className="border-y border-line py-7 text-sm leading-6 text-ink-muted">Pembukuan publik belum diterbitkan. RT akan menampilkan ringkasan setelah data Kas lama selesai direkonsiliasi.</p>}</div>
    </section>
  </main>;
}
